In [3]:
# scikit-learnのデータベースの利用を宣言
from sklearn import datasets
# アヤメデータを読み込む
iris = datasets.load_iris()
# データの説明を表示
print(iris.DESCR)

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)
    ============== ==== ==== ======= ===== ====================

    :Missing Attribute Values: None
  

In [4]:
iris.data

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [5]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
type(iris.data)

numpy.ndarray

In [1]:
from sklearn.model_selection import train_test_split as split
X_train, X_test, y_train, y_test = split(iris.data, iris.target, train_size=0.8)

In [30]:
list(zip(X_train.tolist(), y_train))

[([5.4, 3.4, 1.7, 0.2], 2),
 ([6.2, 3.4, 5.4, 2.3], 1),
 ([5.6, 2.7, 4.2, 1.3], 2),
 ([6.9, 3.1, 4.9, 1.5], 0),
 ([4.8, 3.0, 1.4, 0.3], 0),
 ([5.0, 3.4, 1.6, 0.4], 1),
 ([7.2, 3.6, 6.1, 2.5], 0),
 ([6.3, 3.4, 5.6, 2.4], 1),
 ([5.1, 3.4, 1.5, 0.2], 0),
 ([5.2, 4.1, 1.5, 0.1], 2),
 ([6.4, 2.9, 4.3, 1.3], 2),
 ([5.3, 3.7, 1.5, 0.2], 0),
 ([4.4, 3.2, 1.3, 0.2], 0),
 ([5.1, 3.5, 1.4, 0.3], 1),
 ([6.3, 2.5, 4.9, 1.5], 1),
 ([5.7, 2.8, 4.1, 1.3], 2),
 ([6.9, 3.1, 5.4, 2.1], 0),
 ([5.5, 2.4, 3.8, 1.1], 1),
 ([5.7, 4.4, 1.5, 0.4], 2),
 ([5.2, 3.5, 1.5, 0.2], 0),
 ([5.6, 2.8, 4.9, 2.0], 1),
 ([5.6, 3.0, 4.5, 1.5], 1),
 ([5.8, 2.7, 3.9, 1.2], 2),
 ([5.9, 3.0, 5.1, 1.8], 0),
 ([4.8, 3.4, 1.9, 0.2], 0),
 ([6.3, 2.3, 4.4, 1.3], 1),
 ([6.1, 3.0, 4.9, 1.8], 0),
 ([6.3, 2.5, 5.0, 1.9], 2),
 ([6.7, 3.1, 4.4, 1.4], 1),
 ([6.2, 2.8, 4.8, 1.8], 2),
 ([7.4, 2.8, 6.1, 1.9], 0),
 ([6.0, 2.7, 5.1, 1.6], 1),
 ([6.4, 2.7, 5.3, 1.9], 0),
 ([5.0, 3.2, 1.2, 0.2], 1),
 ([6.5, 2.8, 4.6, 1.5], 1),
 ([4.8, 3.1, 1.6, 0.

In [33]:
import random, numpy as np

# 二つのリストを合成
d = list(zip(iris.data.tolist(), iris.target))

# シャッフル
random.shuffle(d)

# 8:2の割合で分ける
train_data = d[0:130]
test_data = d[130:150]

# 合成したリストを分離する
x_train, y_train = zip(*train_data)
x_test, y_test = zip(*test_data)
np.array(x_train)

array([[ 6.7,  3.1,  4.4,  1.4],
       [ 6.1,  2.6,  5.6,  1.4],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 6.1,  2.8,  4.7,  1.2],
       [ 6.9,  3.1,  5.4,  2.1],
       [ 6.4,  3.2,  4.5,  1.5],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 6. ,  2.2,  4. ,  1. ],
       [ 5.8,  2.7,  3.9,  1.2],
       [ 5.8,  2.6,  4. ,  1.2],
       [ 5.7,  2.8,  4.5,  1.3],
       [ 7.7,  2.8,  6.7,  2. ],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 6.9,  3.2,  5.7,  2.3],
       [ 5.6,  3. ,  4.1,  1.3],
       [ 5.5,  2.5,  4. ,  1.3],
       [ 6.8,  3. ,  5.5,  2.1],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 6.3,  2.3,  4.4,  1.3],
       [ 6.8,  2.8,  4.8,  1.4],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 7.7,  3. ,  6.1,  2.3],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 7.6,  3. ,  6.6,  2.1],
       [ 6.7,  3. ,  5.2,  2.3],
       [ 4.8,  3.1,  1.6,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 7.7,  2.6,  6.9,  2.3],
       [ 5.5,  4.2,  1.4,  0.2],
       [ 6.4,  2.8,  5.6,  2.2],
       [ 6

In [8]:
a = ["a", "b", "c", "d", "e"]
b = [1, 2, 3, 4, 5]
c = list(zip(a, b))
print(c)

[('a', 1), ('b', 2), ('c', 3), ('d', 4), ('e', 5)]


In [37]:
a, b = zip(*c)

In [38]:
a

('a', 'b', 'c', 'd', 'e')

In [39]:
b

(1, 2, 3, 4, 5)

In [43]:
from sklearn import svm
# モデルを生成
clf = svm.SVC()
# データを学習
clf.fit(x_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [44]:
# テストデータを利用して予測
pred = clf.predict(x_test)
# 予測が答えと、どれくらい合っているかカウント
result = list(pred == y_test).count(True) / len(y_test)
print("正解率=" + str(result))

正解率=1.0


In [48]:
cnt = 0
for pre, y in zip(pred, y_test):
    result = (pre == y)
    print(pre, y, result)
    if result: cnt += 1
print("{0}/{1}={2}".format(cnt, len(y_test), cnt / len(y_test)))

1 1 True
2 2 True
0 0 True
2 2 True
0 0 True
0 0 True
0 0 True
2 2 True
2 2 True
1 1 True
2 2 True
2 2 True
2 2 True
2 2 True
2 2 True
0 0 True
2 2 True
0 0 True
1 1 True
2 2 True
20/20=1.0


In [49]:
from sklearn.model_selection import train_test_split as split
x_train, x_test, y_train, y_test = split(iris.data, iris.target, train_size=0.8)


In [51]:
list(zip(x_train, y_train))

[(array([ 6.2,  2.8,  4.8,  1.8]), 2),
 (array([ 7.2,  3.6,  6.1,  2.5]), 2),
 (array([ 5.4,  3. ,  4.5,  1.5]), 1),
 (array([ 5.7,  3. ,  4.2,  1.2]), 1),
 (array([ 4.6,  3.2,  1.4,  0.2]), 0),
 (array([ 6.7,  3. ,  5. ,  1.7]), 1),
 (array([ 6.4,  2.8,  5.6,  2.1]), 2),
 (array([ 4.6,  3.6,  1. ,  0.2]), 0),
 (array([ 7.7,  3.8,  6.7,  2.2]), 2),
 (array([ 5.7,  2.6,  3.5,  1. ]), 1),
 (array([ 5.4,  3.9,  1.3,  0.4]), 0),
 (array([ 6.2,  2.9,  4.3,  1.3]), 1),
 (array([ 4.3,  3. ,  1.1,  0.1]), 0),
 (array([ 7.2,  3.2,  6. ,  1.8]), 2),
 (array([ 6.3,  3.3,  4.7,  1.6]), 1),
 (array([ 6.5,  3. ,  5.8,  2.2]), 2),
 (array([ 6.4,  2.9,  4.3,  1.3]), 1),
 (array([ 6.4,  2.7,  5.3,  1.9]), 2),
 (array([ 4.8,  3.4,  1.9,  0.2]), 0),
 (array([ 7.7,  2.8,  6.7,  2. ]), 2),
 (array([ 6.3,  2.9,  5.6,  1.8]), 2),
 (array([ 5.5,  2.3,  4. ,  1.3]), 1),
 (array([ 6.4,  3.1,  5.5,  1.8]), 2),
 (array([ 7.4,  2.8,  6.1,  1.9]), 2),
 (array([ 7.7,  3. ,  6.1,  2.3]), 2),
 (array([ 6.7,  3.1,  5.6

In [62]:
a = [1, 2, 3, 4, 5]
b = ['a', 'b', 'c', 'd', 'e']
print(list(zip(a, b))


SyntaxError: unexpected EOF while parsing (<ipython-input-62-2ac33d1b6386>, line 3)